apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: development-

commonLabels:
  env: development
  app: mongo

bases:
- ../../base

patches:
- resources_limit.yaml

replicas:
- name: mongo
  count: 1
