apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  template:
    spec:
      containers:
        - name: mongodb
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
