apiVersion: v1
kind: Service
metadata:
  name: {{ include "plain.fullname" . }}-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plain.selectorLabels" . | nindent 4 }}
