apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  app.cfg: |
    DEBUG=True
    SECRET_KEY=b'zkwDBJ&^4kSm_eUJ'
    MONGODB_HOST='mongodb://mongo:27017/blog?replicaSet=rs0'
    BLOG_TITLE='K8s Summit Blog'
    BLOG_BANNER_TITLE='Kubernetes 實戰工作坊'
    BLOG_BANNER_SUBTITLE='帶你從無到有打造 Kubernetes 的環境'