apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}-config
data:
  app.cfg: |
    DEBUG=True
    SECRET_KEY=b'zkwDBJ&^4kSm_eUJ'
    MONGODB_HOST='mongodb://mongo:27017/blog?replicaSet=rs0'
    BLOG_TITLE={{ quote .Values.blog.title }}
    BLOG_BANNER_TITLE={{ quote .Values.blog.banner.title }}
    BLOG_BANNER_SUBTITLE={{ quote .Values.blog.banner.subtitle }}
    BLOG_BANNER_COLOR={{ quote .Values.blog.banner.color }}
