apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
spec:
  selector:
    app: {{ include "flask-app.fullname" . }}
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
