apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app
  targetCPUUtilizationPercentage: 50