apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "flask-app.fullname" . }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "flask-app.fullname" . }}
          servicePort: 5000
